### ISSUE TITLE
sss

### ISSUE THREAD

**Issue by GGGitBoy** [GGGitBoy/personal#15]
### 部署步骤

1. 添加环境变量PANDARIA_PROMETHEUS_METRICS=true
2. 开启监控
3. 创建secret
- 获取API&Keys
<img width="935" alt="截屏2021-08-21 上午1 29 03" src="https://user-images.githubusercontent.com/51182588/130271602-17a1f794-4ec2-4d04-b14f-85def2bdaf94.png">

- 添加secret
```
apiVersion: v1
data:
  token: <api-token>  (上面获取的token)
kind: Secret
metadata:
  name: rancher-metrics
  namespace: cattle-system
type: Opaque
```
4. 创建servicemonitor

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rancher-metrics
  name: rancher-metrics
  namespace: cattle-system
spec:
  clusterIP: None
  ports:
  - name: metrics443
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: rancher
  sessionAffinity: None
  type: ClusterIP
```

添加servicemonitor

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rancher
  namespace: cattle-system
spec:
  endpoints:
  - port: metrics443
    targetPort: 443
    path: "/metrics"
    scheme: "https"
    tlsConfig:
      caFile: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
      insecureSkipVerify: true
    bearerTokenSecret:
      key: token
      name: rancher-metrics
  selector:
    matchLabels:
      app: rancher-metrics
```

5. 添加告警规则

### 额外参数设置

默认将集群error、unavailable、failed时设为不可用，即会发送告警，可通过添加环境变量PANDARIA_METRICS_CLUSTER_STATE_CHECK自定义告警状态

配置示例
PANDARIA_METRICS_CLUSTER_STATE_CHECK=error,unavailable (多个状态时用","隔开)
